### PR TITLE
Changing outputPath to resolve to root

### PR DESCRIPTION
**Pull request by s4m0r4m4**
I changed the way it handles the "outputPath" parameter (formerly called the "out" parameter).

The [angular docs](https://angular.io/cli/build) say build treats outputPath as "The full path for the new output directory, relative to the current workspace."

I wanted to make it so that the nx make command can support the exact same syntax, for example:
`nx make <project-name> --outputPath="\dist\my-executables\my-app"`

Thoughts? I'm happy to make tweaks as needed.

### CODE REVIEW

**Comment by bennymeg** [comment]
Thanks for contributing.

- You need to add `outputPath` to the MakeElectronBuilderOptions interface:
   https://github.com/bennymeg/nx-electron/blob/dc9c13e8d918247a2f7d4ac4b0bf4670b2384a16/src/builders/make/make.impl.ts#L24
- If you add `outputPath` to the options, you will have to delete it in here:
   https://github.com/bennymeg/nx-electron/blob/dc9c13e8d918247a2f7d4ac4b0bf4670b2384a16/src/builders/make/make.impl.ts#L140
- Since you resolved the `out` option, this line will be needed to be modified as well: https://github.com/bennymeg/nx-electron/blob/dc9c13e8d918247a2f7d4ac4b0bf4670b2384a16/src/builders/make/make.impl.ts#L116

**Comment by s4m0r4m4** [comment]
Thanks for the guidance! Ok I made those changes, let me know if anything else looks off.

Just to confirm - this means that angular.json should use 'outputPath' rather than 'out', right? That would bring it in to line with vanilla angular builder projects.

**Comment by s4m0r4m4** [comment]
I also was not happy with the "as any" cast that I had to add in normalizeMakingOptions. I tried reaplacing the generic `T extends ... `with `JsonObject & MakeElectronBuilderOptions` in my last commit. Let me know if you object and I can revert, I'm new to angular plugin building.

**Comment by bennymeg** [comment]
Hi, it seems like it wont work either.

Would you prefer I will guide you to fix it or that I will solve it myself?

**Comment by s4m0r4m4** [comment]
I'd love to learn more here if you're willing to provide guidance. I think the biggest problem is that I don't know how to test my changes to see if they work in the first place. How do you do that?

**Comment by bennymeg** [comment]
Sorry for the late response.

There are test suites, but they are mostly general tests, if needed I write a new test.
Mostly, I have a separate dummy test project with a linked version of the project and I do all the testing there.

I think it will be quicker if I will make add your changes properly and reference your issue and PR in the commit; then I will explain what I've done different and why if you wish.

**Pull request closed without merging**
