### PR TITLE
docs: fix invalid links

### PR DESCRIPTION
**Pull request by sh-himanshu**

### CODE REVIEW

**Comment by sh-himanshu** [comment]
my fix seems invalid so creating an issue instead.

**Comment by bennymeg** [comment]
Hi,
This is seems like a valid fix, could you explain?

**Comment by sh-himanshu** [comment]
Hi @bennymeg ,
I was not sure if those links should be replaced by https://github.com/bennymeg/nx-electron/blob/master/packages/nx-electron/src/validation/maker.schema.json
or https://github.com/bennymeg/nx-electron/blob/master/packages/nx-electron/src/executors/package/schema.json

In case I did it correctly I can update this PR to replace one more dead link

**Comment by bennymeg** [comment]
The one you used is the correct link.
I you could please update the other readme as well while you at it the would be great (It is almost identical to the one you fixed).
Thanks in advance.

**Comment by sh-himanshu** [comment]
Here you go, mate.

**Pull request merged**
