### PR TITLE
Fixing issues with @nrwl/workspace 11+

### PR DESCRIPTION
**Pull request by pascalbayer**
This PR fixes the error `Cannot read property 'cyan' of undefined` mentioned in https://github.com/bennymeg/nx-electron/issues/66 caused by @nrwl/workspace versions > 10, which currently makes `nx-electron` unusable with projects using nx versions > 10.
Basically it just bumps package dependencies of @nrwl/* to 11+ and fixes all other dependencies mentioned as vulnerabilities by npm audit.

### CODE REVIEW

**Comment by bennymeg** [comment]
Does this works for you without upgrading the `angular-devkit` packages to v11?

**Comment by pascalbayer** [comment]
It does work, I've build the new version and already using it successfully in one of my projects. But I guess it makes sense to update it to the versions used internally by @nrwl/workspace to avoid any incompatible interfaces. Will push an update in a few minutes. Thanks for the feedback!

**Comment by pascalbayer** [comment]
I've pushed a few more updates, including the usage of @nrwl/devkit instead of the outdated `import { names, toFileName } from '@nrwl/workspace/src/utils/name-utils';`

**Comment by bennymeg** [comment]
Thank you for taking the time to create this pull request!

I will rebase it to a new branch (feature/v11) so it can be the base for v11. I will release it under v11.0.0-alpha.0 so it will be available for use for everyone.

> Might make sense to include jshint to the devDependencies

No problems.

> I'll try to have a look to setup a platform independent testing setup in the next weeks if I have some time available.

Tnx again!

**Pull request merged**
