### PR TITLE
Resolve several issues after NX 16 upgrade

### PR DESCRIPTION
**Pull request by WillPoulson**
Hi @bennymeg,

I recently installed and used nx-electron for a project this week and stumbled into a few issues using the new v16 alpha release.

The first issue I encountered was that the generator for the app wasn't working, I think this was an accident introduced by the initial upgrade pr #219 this was also raised in #217

The second issue I encountered was that the dep version for nx/workspace was quite restrictive, our project was running 16.1 which worked fine however npm was enforcing us to upgrade to 16.3 due to nx-electron. I've worked around this using the `overrides` in our project temporally however the much looser requirement of 16+ should be a bit more friendly for people.

Whilst doing the above changes I've also attempted to tidy up a few bits.

I've got two of the specs now passing and attempted the others but soon reverted my changes. It's potentially a re-write job for those which I'm happy to look at in the future.

I've also tidied up some unused deps that were hanging around in the project. When running the generator myself the post install script section wasn't working. It appeared to all continue okay without this section so I've removed the part of the generator that was trying to add it. As a result exitzero is no longer a required dep to add when running the generator.

I'd like to contribute more to this project in the future but thought I'd take it slow for my initial PR here. Thanks for your work on this project 🎉

### CODE REVIEW

**Comment by bennymeg** [comment]
Thank you for contributing! this is much appreciated.
My only concern is regarding the last commit, `install-app-deps` is meant to recompile native dependencies to the electron abi (rather than the node abi). It might be [optional](https://github.com/electron-userland/electron-builder/issues/1906), but I think it's a good practice to leave it in, or at least add another script that rebuild native dependencies.

**Comment by WillPoulson** [comment]
@bennymeg No problem at all.

Ah yeah after reading that issue that you linked I agree. I'm quite new to the electron world so I had no idea what it was accomplishing to be honest 😅.

Do you think it's safe to remove the `exitzero` dependency here?
Based from the electron-builder documentation they don't specify it's needed.

If so I can revert that last commit but remove the `exitzero` part.

**Comment by bennymeg** [comment]
I guess you can remove it, I think I added it only for CI/CD proposes.

**Comment by WillPoulson** [comment]
Cool @bennymeg

That's all updated, postinstall script back where it was but without the exitzero dep.

This PR certainly doesn't fix _everything_ introduced from the NX 16 upgrade but it's hopefully a good start. Happy to contribute more in the future 😄

**Pull request merged**
