### PR TITLE
make build scripts cross platform

### PR DESCRIPTION
**Pull request by ericwooley**
Updated the npm scripts to be cross platform using [shx](https://github.com/shelljs/shx).

Seems to fix https://github.com/bennymeg/nx-electron/issues/66 but I am not exactly sure why.

I don't use windows, so after making the scripts cross platform, and using `yarn link` to test, everything seems to just be working :man_shrugging:

I would give this a quick test on windows though. It *should* work cross platform. But is untested.

### CODE REVIEW

**Comment by bennymeg** [comment]
Thanks, I did not know that a package like `shx` exists, looks awesome.
Do you mind making a PR to a new branch? I would like to test on windows as well before merging it into the master branch.

**Comment by ericwooley** [comment]
@bennymeg 

I'd be happy to change the base, but I think you need to make a new branch on your repo. I don't believe I can make a PR to a new branch.

**Comment by ericwooley** [comment]
update on #66 

This does not seem to solve the issue after all. Builds work when the package is linked, but not when installed the normal way. Will comment with more details on the issue.

**Comment by bennymeg** [comment]
No problem. I've opened the following branch: `feature/x-platform-build-scripts`

**Pull request merged**
