### PR TITLE
feat(nx-electron): update to NX 20

### PR DESCRIPTION
**Pull request by conor-mac-aoidh**
- changes to executor for NX 20
- update deps & peer deps

### CODE REVIEW

**Comment by glani** [comment]
can we speed up this PR somehow? It is annoying to do npm link from the feature branch of the author everytime.

@conor-mac-aoidh well done.

**Review by bennymeg — APPROVED** [review]

**Comment by bennymeg** [comment]
Tnx

**Comment by glani** [comment]
you can even use the master build with npm link but it is annoying to relink after every npm install

**Comment by bennymeg** [comment]
published as alpha

**Pull request merged**
